/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/agent/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Agent Ask
         * @description 运行独立 Agent Lab；最多五步，只能调用白名单只读工具。
         */
        post: operations["agent_ask_api_agent_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask
         * @description 流式回答。支持用户中断：前端 abort 后，这里会停止向上游模型要 token。
         *
         *     刻意写成 async def（而不是同步 def）：只有在协程里才能 await 出让控制权，
         *     从而定期检查 `request.is_disconnected()`。写成同步函数时 FastAPI 会丢进线程池，
         *     客户端断开后那个线程仍会把生成跑到底——白烧本地 GPU，或继续消耗用户的
         *     Claude/GLM 付费额度。这不是优化，是避免"用户点了停止还在扣他的钱"。
         */
        post: operations["ask_api_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Books */
        get: operations["list_books_api_books_get"];
        put?: never;
        /** Upload Books */
        post: operations["upload_books_api_books_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Book */
        delete: operations["delete_book_api_books__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/index-tasks/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Index Task */
        get: operations["current_index_task_api_index_tasks_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/index-tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Index Task */
        get: operations["get_index_task_api_index_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/index-tasks/{task_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Index Task */
        post: operations["cancel_index_task_api_index_tasks__task_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/index-tasks/{task_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Index Task */
        post: operations["retry_index_task_api_index_tasks__task_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Model */
        post: operations["set_model_api_model_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_api_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reindex
         * @description 启动后台同步。默认只处理变化文件；force=true 强制重新处理所有现存书。
         */
        post: operations["reindex_api_reindex_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description 在本地小说原文中做精确全文搜索，不经过大模型。
         */
        get: operations["search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session
         * @description 读回某个会话的全部对话，用于刷新页面后恢复界面。
         */
        get: operations["get_session_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentAskRequest */
        AgentAskRequest: {
            /**
             * Max Steps
             * @default 5
             */
            max_steps: number;
            /** Question */
            question: string;
            /** Session Id */
            session_id?: string | null;
        };
        /** AgentStep */
        AgentStep: {
            /** Args */
            args?: {
                [key: string]: unknown;
            };
            /** Observation */
            observation: string;
            /** Reason */
            reason: string;
            /** Run Id */
            run_id?: string | null;
            /** Source Ids */
            source_ids?: string[];
            /** Step */
            step: number;
            /** Tool */
            tool: string;
        };
        /**
         * AnswerMode
         * @description 用户选择的问答模式；值也是前后端 API 契约的一部分。
         * @enum {string}
         */
        AnswerMode: "auto" | "grounded" | "free";
        /** AskRequest */
        AskRequest: {
            /** @default auto */
            mode: components["schemas"]["AnswerMode"];
            /** Question */
            question: string;
            /** Session Id */
            session_id?: string | null;
            /**
             * Top K
             * @default 3
             */
            top_k: number;
        };
        /** Body_upload_books_api_books_post */
        Body_upload_books_api_books_post: {
            /** Files */
            files: string[];
        };
        /** BookList */
        BookList: {
            /** Books */
            books: string[];
        };
        /** CurrentModel */
        CurrentModel: {
            /** Current */
            current: string;
        };
        /** DeleteResult */
        DeleteResult: {
            /** Deleted */
            deleted: string;
            task: components["schemas"]["IndexTaskStatus"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthStatus */
        HealthStatus: {
            /** Ok */
            ok: boolean;
            /** Ready */
            ready: boolean;
        };
        /** IndexResult */
        IndexResult: {
            /** Added */
            added?: string[];
            /** Chunk Count */
            chunk_count: number;
            /**
             * Contextualized
             * @default 0
             */
            contextualized: number;
            /** Deleted */
            deleted?: string[];
            /**
             * Hierarchy Nodes
             * @default 0
             */
            hierarchy_nodes: number;
            /** Modified */
            modified?: string[];
            /** Novels */
            novels: string[];
            /**
             * Relations
             * @default 0
             */
            relations: number;
            /** Unchanged */
            unchanged?: string[];
        };
        /** IndexTaskStatus */
        IndexTaskStatus: {
            /** Created At */
            created_at: string;
            /** Error */
            error?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /**
             * Force
             * @default false
             */
            force: boolean;
            /** Id */
            id: string;
            /** Message */
            message: string;
            /** Progress */
            progress: number;
            result?: components["schemas"]["IndexResult"] | null;
            /** Retry Of */
            retry_of?: string | null;
            /** Stage */
            stage: string;
            /** Started At */
            started_at?: string | null;
            /** Status */
            status: string;
        };
        /** ModelList */
        ModelList: {
            /** Current */
            current: string;
            /** Models */
            models: string[];
        };
        /** RetrievalCandidate */
        RetrievalCandidate: {
            /** Chapter Title */
            chapter_title?: string | null;
            /** Chunk Id */
            chunk_id: number;
            /** Novel */
            novel: string;
            /** Previous Rank */
            previous_rank?: number | null;
            /** Rank */
            rank: number;
            /** Score */
            score?: number | null;
            /** Score Label */
            score_label?: string | null;
            /**
             * Selected
             * @default false
             */
            selected: boolean;
        };
        /** SearchMatch */
        SearchMatch: {
            /** Chapter Title */
            chapter_title?: string | null;
            /** Chunk Id */
            chunk_id: number;
            /** Match Count */
            match_count: number;
            /** Novel */
            novel: string;
            /** Text */
            text: string;
        };
        /** SearchResult */
        SearchResult: {
            /** Query */
            query: string;
            /** Results */
            results: components["schemas"]["SearchMatch"][];
            /** Total */
            total: number;
        };
        /** SessionHistory */
        SessionHistory: {
            /** Session Id */
            session_id: string;
            /** Turns */
            turns: components["schemas"]["StoredTurn"][];
        };
        /** SetModelRequest */
        SetModelRequest: {
            /** Model */
            model: string;
        };
        /** SourceItem */
        SourceItem: {
            /** Chapter Title */
            chapter_title?: string | null;
            /** Chunk Id */
            chunk_id: number;
            /** Novel */
            novel: string;
            /** Text */
            text: string;
        };
        /** StoredTurn */
        StoredTurn: {
            /** Agent Steps */
            agent_steps?: components["schemas"]["AgentStep"][] | null;
            /** Content */
            content: string;
            /** Role */
            role: string;
            /** Run Config */
            run_config?: {
                [key: string]: unknown;
            } | null;
            /** Sources */
            sources?: components["schemas"]["SourceItem"][] | null;
            /** Status */
            status: string;
            /** Trace */
            trace?: components["schemas"]["TraceStep"][] | null;
            /** Turn Index */
            turn_index: number;
        };
        /** TraceStep */
        TraceStep: {
            /** Candidates */
            candidates?: components["schemas"]["RetrievalCandidate"][];
            /** Detail */
            detail: string;
            /** Evidence Tokens */
            evidence_tokens?: number | null;
            /** Expansion Mode */
            expansion_mode?: string | null;
            /** Ms */
            ms?: number | null;
            /** Reasons */
            reasons?: string[];
            /** Stage */
            stage?: string | null;
            /** Stage Key */
            stage_key?: string | null;
            /** Step */
            step: string;
            /** Still No Evidence */
            still_no_evidence?: boolean | null;
            /** Truncated */
            truncated?: boolean | null;
            /** Truncation Reason */
            truncation_reason?: string | null;
            /** Variants */
            variants?: string[];
        };
        /** UploadResult */
        UploadResult: {
            /** Saved */
            saved: string[];
            task: components["schemas"]["IndexTaskStatus"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    agent_ask_api_agent_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentAskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_api_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_books_api_books_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookList"];
                };
            };
        };
    };
    upload_books_api_books_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_books_api_books_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_book_api_books__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    current_index_task_api_index_tasks_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexTaskStatus"] | null;
                };
            };
        };
    };
    get_index_task_api_index_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexTaskStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_index_task_api_index_tasks__task_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexTaskStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_index_task_api_index_tasks__task_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexTaskStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_model_api_model_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetModelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_api_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelList"];
                };
            };
        };
    };
    reindex_api_reindex_post: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexTaskStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_search_get: {
        parameters: {
            query: {
                q: string;
                book?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionHistory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
